### ISSUE TITLE
How to Install ?

### ISSUE THREAD

**Issue by souhaiebtar** [wfxr/dotfiles#2]
@wfxr i tried to install it on my clean ubuntu install but i can't get it to look like in the picture, any help please on how to do it.

**Comment by wfxr** [comment]
Hi @souhaiebtar This repository mainly contains my configurations. To make it work you should install corresponding programs first. I do not use ubuntu for some years so your should carefully check the ubuntu setup script and choose what you want.

It should be not too hard to get your terminal look like the screenshot in README. The `zsh` theme was [spaceship](https://github.com/denysdovhan/spaceship-prompt). The `vim` theme was [gruvbox](https://github.com/morhetz/gruvbox). The `tmux` theme was [tmuxpower](https://github.com/wfxr/tmux-power). And the `git log viewer` was [forgit](https://github.com/wfxr/forgit) with [diff-so-fancy](https://github.com/so-fancy/diff-so-fancy).

Anyway this repo is not the framework to be used out of the box for everyone like [spacevim](https://github.com/SpaceVim/SpaceVim) or [oh-my-zsh](https://github.com/ohmyzsh/ohmyzsh). You'd better reference it instead of using it directly.
